apiVersion: v1
kind: Service
metadata:
  name: apigw-test-ms
  labels:
    app: apigw-test-ms
spec:
  type: NodePort
  ports:
    # ports that this service should serve on
    -
      name: 'servlet-http'
      port: 8081
      targetPort: 8081
      nodePort:
    -
      name: 'servlet-https'
      port: 8444
      targetPort: 8444
      nodePort:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: apigw-test-ms